#!/usr/bin/env pwsh
# Create GitHub issues for Spec 009: User Directory
# Repository: microsoft/CommunityManagement-Sample-Spec-Kit

$env:Path += ";$env:LOCALAPPDATA\gh-cli\bin"
$repo = "microsoft/CommunityManagement-Sample-Spec-Kit"

# Define all issues as structured data
$issues = @(
    # Phase 1: Setup
    @{ id="T001"; title="Create directory structure per plan.md"; phase="phase:setup"; priority="priority:P1"; parallel=$false; story=""; body="Create directory structure per plan.md:`n- apps/web/src/lib/directory/`n- apps/web/src/components/directory/`n- apps/web/src/app/api/directory/`n- apps/web/src/app/directory/`n- apps/web/tests/integration/directory/`n- packages/shared-ui/src/DirectoryCard/`n- packages/shared-ui/src/SocialIcons/`n`n**Spec**: specs/009-user-directory/spec.md" }
    @{ id="T002"; title="Create migration 009_user_directory.sql"; phase="phase:setup"; priority="priority:P1"; parallel=$false; story=""; body="Create database migration file apps/web/src/db/migrations/009_user_directory.sql`n- ALTER TABLE user_profiles ADD COLUMN directory_visible BOOLEAN NOT NULL DEFAULT false`n- Expand social_links platform CHECK constraint from 4 to 8 values`n- Create 5 partial indexes per data-model.md`n`n**Spec**: specs/009-user-directory/data-model.md" }
    @{ id="T003"; title="Create shared directory types"; phase="phase:setup"; priority="priority:P1"; parallel=$true; story=""; body="Create shared directory types in packages/shared/src/types/directory.ts`n- DirectoryEntry, DirectoryQueryParams, DirectoryResponse`n- DirectorySortMode, RelationshipFilter, RelationshipStatus`n- VisibleSocialLink, ProfileCompleteness`n`n**Contract**: specs/009-user-directory/contracts/directory-api.ts" }
    @{ id="T004"; title="Expand SocialPlatform type to 8 values"; phase="phase:setup"; priority="priority:P1"; parallel=$true; story=""; body="Expand SocialPlatform type in packages/shared/src/types/community.ts`nAdd: tiktok, twitter_x, linkedin, threads to existing 4-value union type`n`n**FR**: FR-023`n**Research**: R-1" }
    @{ id="T005"; title="Create Zod validation schemas for directory"; phase="phase:setup"; priority="priority:P1"; parallel=$true; story=""; body="Create Zod validation schemas in apps/web/src/lib/directory/schemas.ts`n- DirectoryQueryParamsSchema (cursor, pageSize 1-100 default 20, sort, role, city, country, continent, teachersOnly, relationship, search)`n- CursorSchema for decode validation" }
    @{ id="T006"; title="Create PGlite test seed helpers"; phase="phase:setup"; priority="priority:P1"; parallel=$true; story=""; body="Create PGlite test seed helpers in apps/web/tests/integration/directory/helpers.ts`n- seedDirectoryUsers() creating 10+ users with varied directory_visible states, roles, cities, teacher profiles, social links at various visibility levels, follow/block pairs, and mutual follows (friends)" }

    # Phase 2: Foundational
    @{ id="T007"; title="Implement cursor encode/decode utilities"; phase="phase:foundational"; priority="priority:P1"; parallel=$false; story=""; body="Implement cursor encode/decode utilities in apps/web/src/lib/directory/cursor.ts`n- encodeCursor(sortValue, id) -> base64 opaque string`n- decodeCursor(cursor) -> validated {sortValue, id} with Zod`n`n**Research**: R-2" }
    @{ id="T008"; title="Implement base directory SQL query builder"; phase="phase:foundational"; priority="priority:P1"; parallel=$false; story=""; body="Implement base directory SQL query builder in apps/web/src/lib/directory/service.ts`n- Core SELECT joining user_profiles + geography + teacher_profiles + social_links`n- Block exclusion via NOT EXISTS (symmetric)`n- Social link visibility FILTER clause`n- GROUP BY, LIMIT pageSize+1, self-exclusion`n`n**Research**: R-4, R-6" }
    @{ id="T009"; title="Update Zod SocialPlatform schema to 8 values"; phase="phase:foundational"; priority="priority:P1"; parallel=$true; story=""; body="Update existing Zod SocialPlatform schema in apps/web/src/lib/validation/community-schemas.ts (or equivalent) to match expanded 8-value enum. Ensure Spec 002 validation layer accepts new platforms." }

    # Phase 3: US1 Browse (P1 MVP)
    @{ id="T010"; title="Test: directory lists only visible members"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US1"; body="Integration test: directory lists only visible members + excludes self`nFile: apps/web/tests/integration/directory/directory-listing.test.ts`n- Seed 5 visible + 2 hidden users`n- Assert hidden users absent, assert viewer absent`n`n**FR**: FR-001, FR-004" }
    @{ id="T011"; title="Test: cursor pagination + hasNextPage"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US1"; body="Integration test: cursor pagination + hasNextPage`nFile: apps/web/tests/integration/directory/directory-listing.test.ts`n- Seed 25 visible users, fetch page 1 (20), assert hasNextPage=true + nextCursor`n- Fetch page 2, assert 5 results + hasNextPage=false`n`n**FR**: FR-003" }
    @{ id="T012"; title="Implement getDirectoryPage() service"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US1"; body="Implement getDirectoryPage() in apps/web/src/lib/directory/service.ts`n- Accepts DirectoryQueryParams + viewerId`n- Executes base query with directory_visible=true filter`n- Cursor pagination, returns {entries, nextCursor, hasNextPage}`n`n**FR**: FR-001, FR-003, FR-004" }
    @{ id="T013"; title="Implement GET /api/directory route"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US1"; body="Implement GET /api/directory route in apps/web/src/app/api/directory/route.ts`n- requireAuth(), parse + validate query params with DirectoryQueryParamsSchema`n- Call getDirectoryPage(), return DirectoryResponse`n- 401 on unauth, 400 on invalid params" }
    @{ id="T014"; title="Create DirectoryCard component (5-file)"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US1"; body="Create DirectoryCard component in packages/shared-ui/src/DirectoryCard/`n- 5-file pattern: DirectoryCard.tsx, DirectoryCard.test.tsx, DirectoryCard.stories.tsx, index.web.tsx, index.native.tsx`n- Display avatar (with placeholder fallback), display name, home city, default role badge`n- Verified teacher badge slot, social icons slot`n`n**FR**: FR-002" }
    @{ id="T015"; title="Create DirectoryList component"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US1"; body="Create DirectoryList component in apps/web/src/components/directory/DirectoryList.tsx`n- Renders list of DirectoryCard`n- Load more button triggers cursor-based next-page fetch`n- Manages entries + pagination state`n`n**FR**: FR-003" }
    @{ id="T016"; title="Create directory browse page"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US1"; body="Create directory browse page in apps/web/src/app/directory/page.tsx`n- Server component for initial data fetch`n- Hydrate DirectoryList with first page of results`n`n**FR**: FR-001" }
    @{ id="T017"; title="Add loading skeleton and empty state"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US1"; body="Add loading skeleton and empty state to directory page`n- Skeleton cards during fetch`n- 'No members found' empty state with i18n-ready string`n`n**FR**: FR-001`n**Edge case**: Zero results" }

    # Phase 4: US2 Search/Filter (P1)
    @{ id="T018"; title="Test: role filter returns correct subset"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US2"; body="Integration test: role filter`nFile: apps/web/tests/integration/directory/directory-filters.test.ts`n- Seed users with Base/Flyer/Hybrid roles`n- Filter role=flyer, assert only Flyers returned`n`n**FR**: FR-005" }
    @{ id="T019"; title="Test: location filters (city/country/continent)"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US2"; body="Integration test: location filters`nFile: apps/web/tests/integration/directory/directory-filters.test.ts`n- Seed users across Bristol/London/Paris`n- Filter country=UK, assert only UK users`n`n**FR**: FR-006" }
    @{ id="T020"; title="Test: teacher filter + text search + AND"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US2"; body="Integration test: teacher filter + text search + AND combination`nFile: apps/web/tests/integration/directory/directory-filters.test.ts`n- Seed verified/unverified teachers, filter teachersOnly=true + search='Mar'`n- Assert AND logic`n`n**FR**: FR-008, FR-009, FR-011" }
    @{ id="T020a"; title="Test: sort order (alphabetical + recent)"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US2"; body="Integration test: alphabetical sort returns A-Z order and recently-joined sort returns newest-first`nFile: apps/web/tests/integration/directory/directory-sort.test.ts`n- Seed 5 users with known names and creation dates`n- Verify sort order for both modes`n`n**FR**: FR-010`n**US2-AS7**: recently joined sort" }
    @{ id="T021"; title="Add role filter clause to query builder"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Add role filter clause to directory query builder in apps/web/src/lib/directory/service.ts`n- Append AND p.default_role = $role when role param present`n`n**FR**: FR-005" }
    @{ id="T022"; title="Add location filter clauses to query builder"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Add location filter clauses to directory query builder in apps/web/src/lib/directory/service.ts`n- city/country/continent via geography JOIN`n- AND g.city = $city / g.country / g.continent, mutually exclusive levels`n`n**FR**: FR-006" }
    @{ id="T023"; title="Add teacher + text search filter clauses"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Add teacher-only and text search filter clauses to directory query builder`nFile: apps/web/src/lib/directory/service.ts`n- Teacher: AND tp.badge_status='verified' AND tp.is_deleted=false`n- Search: AND lower(p.display_name) LIKE lower($search)||'%'`n`n**FR**: FR-008, FR-009" }
    @{ id="T024"; title="Add alphabetical + recent sort modes"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Add alphabetical and recently-joined sort modes to directory query builder`nFile: apps/web/src/lib/directory/service.ts`n- Alphabetical: ORDER BY display_name, id`n- Recent: ORDER BY created_at DESC, id DESC`n- Update cursor encode/decode per sort mode`n`n**FR**: FR-010" }
    @{ id="T025"; title="Create DirectoryFilters component"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Create DirectoryFilters component in apps/web/src/components/directory/DirectoryFilters.tsx`n- Role dropdown (Base/Flyer/Hybrid/All)`n- Location selector (city/country/continent from geography)`n- Teacher toggle, sort selector, text search input`n- Clear-all button`n`n**FR**: FR-005 through FR-012" }
    @{ id="T026"; title="Integrate DirectoryFilters with page"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US2"; body="Integrate DirectoryFilters with directory page`n- Sync filter state to URL search params`n- Re-fetch API on filter change, reset cursor on filter change`n- Clear-all resets to unfiltered view`n`n**FR**: FR-011, FR-012" }

    # Phase 5: US3 Visibility (P1)
    @{ id="T027"; title="Test: directory_visible default + toggle"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US3"; body="Integration test: default directory_visible=false and toggle behavior`nFile: apps/web/tests/integration/directory/directory-visibility.test.ts`n- Create user, assert not in directory`n- Toggle on via PATCH, assert in directory`n- Toggle off, assert absent`n`n**FR**: FR-013, FR-014" }
    @{ id="T028"; title="Test: GDPR export/deletion for directoryVisible"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US3"; body="Integration test: GDPR export includes directoryVisible + deletion clears it`nFile: apps/web/tests/integration/directory/directory-visibility.test.ts`n`n**FR**: FR-031, FR-032" }
    @{ id="T028a"; title="Test: direct profile URL works when hidden"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US3"; body="Integration test: direct profile URL works even when directory_visible=false`nFile: apps/web/tests/integration/directory/directory-visibility.test.ts`n- Set user's directory_visible=false`n- GET /api/profiles/:userId as another user`n- Assert 200 with profile data`n`n**FR**: FR-015`n**US3-AS4**" }
    @{ id="T028b"; title="Test: 401 for unauthenticated PATCH toggle"; phase="phase:core"; priority="priority:P1"; parallel=$true; story="US3"; body="Integration test: PATCH /api/profiles/me returns 401 for unauthenticated requests and only updates own profile`nFile: apps/web/tests/integration/directory/directory-visibility.test.ts`n- Verify auth enforcement on directoryVisible toggle`n`n**QG-10**: Permission smoke test" }
    @{ id="T029"; title="Extend PATCH /api/profiles/me for visibility"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US3"; body="Extend PATCH /api/profiles/me to accept directoryVisible field`n- Update Zod request schema in existing route`n- Add directory_visible column to UPDATE SQL`n`n**FR**: FR-014" }
    @{ id="T030"; title="Create DirectoryVisibilityToggle component"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US3"; body="Create DirectoryVisibilityToggle component`nFile: apps/web/src/components/directory/DirectoryVisibilityToggle.tsx`n- Labeled toggle switch with i18n-ready label`n- Calls PATCH /api/profiles/me`n`n**FR**: FR-014" }
    @{ id="T031"; title="Add visibility toggle to profile settings"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US3"; body="Add DirectoryVisibilityToggle to profile settings page`nFile: apps/web/src/app/settings/profile/page.tsx`n- Place below existing profile fields`n- Load current state from profile data`n`n**FR**: FR-014" }
    @{ id="T032"; title="Update GDPR export/deletion for directory"; phase="phase:core"; priority="priority:P1"; parallel=$false; story="US3"; body="Update GDPR export in apps/web/src/lib/gdpr/export.ts to include directory_visible`nUpdate GDPR deletion in apps/web/src/lib/gdpr/deletion.ts to clear directory_visible on account delete`n`n**FR**: FR-031, FR-032" }

    # Phase 6: US4 Relationships (P2)
    @{ id="T033"; title="Test: relationship status in directory results"; phase="phase:core"; priority="priority:P2"; parallel=$true; story="US4"; body="Integration test: relationship status indicators in directory results`nFile: apps/web/tests/integration/directory/directory-relationships.test.ts`n- Seed mutual follow (friend), one-way follow, follower, blocked pair`n- Verify viewer_follows/follows_viewer correctly derived`n`n**FR**: FR-019" }
    @{ id="T034"; title="Test: block exclusion is symmetric"; phase="phase:core"; priority="priority:P2"; parallel=$true; story="US4"; body="Integration test: block exclusion is symmetric`nFile: apps/web/tests/integration/directory/directory-relationships.test.ts`n- If A blocks B, B does not see A and A does not see B in directory results`n`n**FR**: FR-016" }
    @{ id="T035"; title="Add relationship status derivation to service"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US4"; body="Add relationship status derivation to directory service response mapping`nFile: apps/web/src/lib/directory/service.ts`n- Map viewer_follows + follows_viewer SQL booleans to RelationshipStatus enum`n- (friend/following/follows_me/none) per DirectoryEntry contract`n`n**FR**: FR-019" }
    @{ id="T036"; title="Add relationship status display to card"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US4"; body="Add relationship status display to DirectoryCard`nFile: packages/shared-ui/src/DirectoryCard/DirectoryCard.tsx`n- Badge/label showing Friend/Following/Follows you/None`n- Style per status`n`n**FR**: FR-019" }
    @{ id="T037"; title="Add follow/unfollow action to DirectoryCard"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US4"; body="Add follow/unfollow action button to DirectoryCard`n- Calls existing POST /api/follows and DELETE /api/follows/:userId`n- Optimistic status toggle without full page reload`n`n**FR**: FR-020, FR-022" }
    @{ id="T038"; title="Add block/unblock action to DirectoryCard"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US4"; body="Add block/unblock action to DirectoryCard`n- Calls existing POST /api/blocks and DELETE /api/blocks/:userId`n- Optimistic removal from DirectoryList on block`n- Confirmation dialog before blocking`n`n**FR**: FR-021, FR-022, FR-016" }

    # Phase 7: US5 Social Icons (P2)
    @{ id="T039"; title="Test: social link visibility filtering"; phase="phase:core"; priority="priority:P2"; parallel=$true; story="US5"; body="Integration test: social link visibility filtering (everyone, followers, friends, hidden)`nFile: apps/web/tests/integration/directory/directory-visibility.test.ts`n- Seed user with links at each visibility level`n- Verify viewer with no relationship sees only 'everyone' links`n- Follower sees 'everyone'+'followers', friend sees all except 'hidden'`n`n**FR**: FR-018" }
    @{ id="T040"; title="Create SocialIcons component (5-file)"; phase="phase:core"; priority="priority:P2"; parallel=$true; story="US5"; body="Create SocialIcons component in packages/shared-ui/src/SocialIcons/`n- 5-file pattern: SocialIcons.tsx, SocialIcons.test.tsx, SocialIcons.stories.tsx, index.web.tsx, index.native.tsx`n- Accepts VisibleSocialLink[], renders platform brand icon per platform`n- Each icon is anchor with target='_blank' rel='noopener noreferrer'`n`n**FR**: FR-023, FR-024, FR-025" }
    @{ id="T041"; title="Create platform icon asset map"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US5"; body="Create platform icon asset map in packages/shared-ui/src/SocialIcons/icons.ts`n- Map SocialPlatform -> SVG icon component for all 8 platforms`n- facebook, instagram, youtube, website, tiktok, twitter_x, linkedin, threads`n`n**FR**: FR-024" }
    @{ id="T042"; title="Integrate SocialIcons into DirectoryCard"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US5"; body="Integrate SocialIcons into DirectoryCard`n- Render below city/role area`n- Hide entire social section when visibleSocialLinks is empty`n`n**FR**: FR-025" }

    # Phase 8: US6 Relationship Filter (P2)
    @{ id="T043"; title="Test: relationship filters (friends/following/etc)"; phase="phase:core"; priority="priority:P2"; parallel=$true; story="US6"; body="Integration test: relationship filters (friends, following, followers, blocked)`nFile: apps/web/tests/integration/directory/directory-relationships.test.ts`n- Seed known relationship graph`n- Verify each filter returns correct subset`n- Verify 'blocked' filter inverts standard block exclusion`n`n**FR**: FR-007" }
    @{ id="T044"; title="Add relationship filter to query builder"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US6"; body="Add relationship filter clauses to directory query builder`nFile: apps/web/src/lib/directory/service.ts`n- friends: mutual follow EXISTS`n- following: viewer follows EXISTS`n- followers: followee=viewer EXISTS`n- blocked: blocker_id=viewer EXISTS (inverts normal block exclusion)`n`n**FR**: FR-007`n**Research**: R-7" }
    @{ id="T045"; title="Add relationship filter to DirectoryFilters"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US6"; body="Add relationship filter dropdown to DirectoryFilters component`nFile: apps/web/src/components/directory/DirectoryFilters.tsx`n- Friends/Following/Followers/Blocked options`n- Combine with other active filters via AND logic`n`n**FR**: FR-007, FR-011" }
    @{ id="T046"; title="Handle Blocked filter special case"; phase="phase:core"; priority="priority:P2"; parallel=$false; story="US6"; body="Handle 'Blocked' filter special case in DirectoryList`n- Show unblock action on each card`n- Skip standard block exclusion for this filter`n- Apply directory_visible=true only for non-blocked filters`n`n**FR**: FR-007`n**US6-AS4**" }

    # Phase 9: US7 Completeness (P3)
    @{ id="T047"; title="Test: computeProfileCompleteness function"; phase="phase:core"; priority="priority:P3"; parallel=$true; story="US7"; body="Unit test: computeProfileCompleteness pure function`nFile: apps/web/src/lib/directory/completeness.test.ts`n- Test all 2^5 field combinations`n- Verify 0% through 100% in 20% increments`n`n**FR**: FR-026, FR-027" }
    @{ id="T048"; title="Implement computeProfileCompleteness()"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US7"; body="Implement computeProfileCompleteness() in apps/web/src/lib/directory/completeness.ts`n- Pure function accepting {avatarUrl, displayName, bio, homeCityId, socialLinkCount}`n- Returns {percentage, fields}`n`n**FR**: FR-026, FR-027`n**Research**: R-5" }
    @{ id="T049"; title="Create ProfileCompleteness component"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US7"; body="Create ProfileCompleteness component in apps/web/src/components/directory/ProfileCompleteness.tsx`n- Progress bar/ring showing percentage`n- Field-by-field breakdown with check/missing indicators`n- i18n-ready labels`n`n**FR**: FR-026" }
    @{ id="T050"; title="Add ProfileCompleteness to settings page"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US7"; body="Add ProfileCompleteness to own profile settings page`nFile: apps/web/src/app/settings/profile/page.tsx`n- Render above directory visibility toggle`n- Pass current profile data`n- Show only for own profile`n`n**FR**: FR-026, FR-028" }

    # Phase 10: US8 Proximity (P3)
    @{ id="T051"; title="Test: proximity sort tiers + fallback"; phase="phase:core"; priority="priority:P3"; parallel=$true; story="US8"; body="Integration test: proximity sort tiers + sub-sort + no-city fallback`nFile: apps/web/tests/integration/directory/directory-proximity.test.ts`n- Seed users in Bristol/London/Paris/Tokyo`n- Verify tier ordering 1->2->3->4 and alphabetical sub-sort within tiers`n- Test viewer with no home city falls back to pure alphabetical`n`n**FR**: FR-029, FR-030" }
    @{ id="T052"; title="Add proximity sort to query builder"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US8"; body="Add proximity sort mode to directory query builder`nFile: apps/web/src/lib/directory/service.ts`n- CASE expression (g.city=viewerCity->1, g.country->2, g.continent->3, ELSE 4) AS proximity_tier`n- ORDER BY proximity_tier ASC, display_name ASC, id ASC`n- Update cursor encode/decode for 3-part proximity cursor`n`n**FR**: FR-029`n**Research**: R-3" }
    @{ id="T053"; title="Handle viewer-no-city fallback"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US8"; body="Handle viewer-no-city fallback in directory service`n- When viewer's home_city_id IS NULL, set all tiers to 4 (global)`n- Degrades to alphabetical sort`n`n**FR**: FR-030" }
    @{ id="T054"; title="Add proximity sort to DirectoryFilters"; phase="phase:core"; priority="priority:P3"; parallel=$false; story="US8"; body="Add 'People near me' proximity sort option to DirectoryFilters sort dropdown`nFile: apps/web/src/components/directory/DirectoryFilters.tsx`n- Labeled 'People near me' with i18n-ready string`n`n**FR**: FR-029" }

    # Phase 11: Polish
    @{ id="T055"; title="Extract all directory UI strings for i18n"; phase="phase:polish"; priority="priority:P2"; parallel=$true; story=""; body="Extract all directory UI strings to i18n namespace in apps/web/src/`n- Filter labels, sort options, empty states ('No members found matching your search')`n- Relationship statuses, 'Show me in the community directory'`n- 'People near me', profile completeness field labels`n`n**FR**: FR-035" }
    @{ id="T056"; title="Accessibility audit for directory page"; phase="phase:polish"; priority="priority:P2"; parallel=$true; story=""; body="Accessibility audit for directory page`n- Keyboard navigation for all filter controls`n- Focus management on load-more`n- ARIA labels on filter dropdowns and toggle`n- Screen reader text for DirectoryCard content`n- Skip-to-content link" }
    @{ id="T057"; title="Add aria-labels to SocialIcons component"; phase="phase:polish"; priority="priority:P2"; parallel=$true; story=""; body="Add aria-labels and sr-only text to SocialIcons component`n- Each icon must have accessible name identifying platform`n- E.g. 'Instagram profile', 'LinkedIn profile'" }
    @{ id="T058"; title="Test: muted users still appear in directory"; phase="phase:polish"; priority="priority:P2"; parallel=$true; story=""; body="Verify muted users still appear in directory results`n- Add regression test confirming mute does NOT affect directory presence`nFile: apps/web/tests/integration/directory/directory-relationships.test.ts`n`n**FR**: FR-017" }
    @{ id="T059"; title="Run quickstart.md end-to-end smoke test"; phase="phase:polish"; priority="priority:P2"; parallel=$false; story=""; body="Run quickstart.md end-to-end smoke test`n- Verify all curl examples work`n- Test commands pass`n- Seed data scenarios produce expected results`n- Migration applies and rolls back cleanly" }
)

$created = 0
$failed = 0

foreach ($issue in $issues) {
    $title = "[009] $($issue.id) - $($issue.title)"
    $labels = @("spec:009-directory", $issue.priority, $issue.phase)
    if ($issue.parallel) { $labels += "parallelizable" }
    
    $storyLabel = ""
    if ($issue.story) { $storyLabel = "`n`n**User Story**: $($issue.story)" }
    
    $body = "$($issue.body)$storyLabel`n`n---`n_Auto-generated from specs/009-user-directory/tasks.md_"
    $labelStr = ($labels -join ",")
    
    try {
        $result = & gh issue create --repo $repo --title $title --body $body --label $labelStr 2>&1
        if ($LASTEXITCODE -eq 0) {
            $created++
            Write-Host "OK  $($issue.id): $result" -ForegroundColor Green
        } else {
            $failed++
            Write-Host "ERR $($issue.id): $result" -ForegroundColor Red
        }
    } catch {
        $failed++
        Write-Host "ERR $($issue.id): $_" -ForegroundColor Red
    }
    
    # Small delay to avoid rate limiting
    Start-Sleep -Milliseconds 500
}

Write-Host "`nDone: $created created, $failed failed" -ForegroundColor Cyan
